# **Numpy**

In [1]:
import numpy as np

In [3]:
np.random.seed(0)
A = np.random.randint(0, 20, [3,6])
A

array([[12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12],
       [ 1,  6,  7, 14, 17,  5]])

# **ndarray methods**

In [10]:
# moyenne
A.mean()

8.777777777777779

In [13]:
# somme de tous le tableau
A.sum()

158

In [14]:
# somme verticale
A.sum(axis=0)

array([22, 40, 25, 21, 26, 24])

In [15]:
# somme horizontale
A.sum(axis=1)

array([40, 68, 50])

In [16]:
# somme cumulée
A.cumsum()

array([ 12,  27,  27,  30,  33,  40,  49,  68,  86,  90,  96, 108, 109,
       115, 122, 136, 153, 158], dtype=int32)

In [18]:
# somme cumulée
A, A.cumsum(axis=0)

(array([[12, 15,  0,  3,  3,  7],
        [ 9, 19, 18,  4,  6, 12],
        [ 1,  6,  7, 14, 17,  5]]),
 array([[12, 15,  0,  3,  3,  7],
        [21, 34, 18,  7,  9, 19],
        [22, 40, 25, 21, 26, 24]], dtype=int32))

In [19]:
# somme cumulée
A, A.cumsum(axis=1)

(array([[12, 15,  0,  3,  3,  7],
        [ 9, 19, 18,  4,  6, 12],
        [ 1,  6,  7, 14, 17,  5]]),
 array([[12, 27, 27, 30, 33, 40],
        [ 9, 28, 46, 50, 56, 68],
        [ 1,  7, 14, 28, 45, 50]], dtype=int32))

In [24]:
# min
A.min()

0

In [25]:
# argmin
A.argmin()

2

In [26]:
# max 
A.max()

19

In [27]:
# argmax
A.argmax()

7

### *SORT*

In [42]:
np.random.seed(0)
B = np.random.randint(0, 10, [2, 5])
B

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4]])

In [44]:
np.exp(B), np.cos(B), np.sin(B)

(array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01, 2.00855369e+01,
         1.09663316e+03],
        [8.10308393e+03, 2.00855369e+01, 1.48413159e+02, 7.38905610e+00,
         5.45981500e+01]]),
 array([[ 0.28366219,  1.        , -0.9899925 , -0.9899925 ,  0.75390225],
        [-0.91113026, -0.9899925 ,  0.28366219, -0.41614684, -0.65364362]]),
 array([[-0.95892427,  0.        ,  0.14112001,  0.14112001,  0.6569866 ],
        [ 0.41211849,  0.14112001, -0.95892427,  0.90929743, -0.7568025 ]]))

## **Statistics** 

In [45]:
B

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4]])

In [46]:
B.var()

5.890000000000001

In [48]:
# equarttype

B.std()

2.4269322199023193

In [51]:
np.corrcoef(B)

array([[1.        , 0.39741307],
       [0.39741307, 1.        ]])

### 'Nombre de répétition d'un element' 

In [54]:
# Nomnbre de répétitions 
B, np.unique(B, return_counts=True)

(array([[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4]]),
 (array([0, 2, 3, 4, 5, 7, 9]), array([1, 1, 3, 1, 2, 1, 1], dtype=int64)))

#### pratique 

In [56]:
values, counts = np.unique(B, return_counts=True)
values, counts

(array([0, 2, 3, 4, 5, 7, 9]), array([1, 1, 3, 1, 2, 1, 1], dtype=int64))

In [57]:
counts.argsort()

array([0, 1, 3, 5, 6, 4, 2], dtype=int64)

### trier values

In [58]:
values[counts.argsort()]

array([0, 2, 4, 7, 9, 5, 3])

In [61]:
for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'element {i} apparait {j} fois')

element 0 apparait 1 fois
element 2 apparait 1 fois
element 4 apparait 1 fois
element 7 apparait 1 fois
element 9 apparait 1 fois
element 5 apparait 2 fois
element 3 apparait 3 fois


## Manque de données

In [62]:
A = np.random.randn(4, 4)
A[0, 2] = np.nan
A[1, 3] = np.nan
A

array([[-0.29139398, -0.13309028,         nan, -1.76165167],
       [-0.08767307,  1.36687937,  1.1253141 ,         nan],
       [ 1.2206081 , -1.33949555,  0.42837337, -0.12346315],
       [ 1.41437719, -0.12405066,  2.00815709,  0.22988654]])

In [63]:
A.mean()

nan

In [64]:
np.nanmean(A)

0.28091267085459537

## compter le nombre de nan

In [65]:
np.isnan(A).sum()

2

In [66]:
np.isnan(A)

array([[False, False,  True, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [67]:
A[np.isnan(A)] = 0
A

array([[-0.29139398, -0.13309028,  0.        , -1.76165167],
       [-0.08767307,  1.36687937,  1.1253141 ,  0.        ],
       [ 1.2206081 , -1.33949555,  0.42837337, -0.12346315],
       [ 1.41437719, -0.12405066,  2.00815709,  0.22988654]])

# Algebre linéaire

In [68]:
X = np.ones((2, 3))
Y = np.ones((3, 2))
X, Y

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

##### transposée

In [69]:
X.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

##### mul matrices

In [70]:
X.dot(Y)

array([[3., 3.],
       [3., 3.]])

In [71]:
Y.dot(X)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

#### Determinant

In [75]:
AA = np.random.randint(0, 5, [3, 3])
AA, np.linalg.det(AA)

(array([[2, 4, 2],
        [0, 0, 4],
        [0, 4, 1]]),
 -31.999999999999986)

In [ ]:
np.linalg.inv(AA)

### vecteur propore

In [77]:
np.linalg.eig(AA)

(array([ 2.        , -3.53112887,  4.53112887]),
 array([[ 1.        ,  0.28985017, -0.85354587],
        [ 0.        , -0.71749602, -0.34481085],
        [ 0.        ,  0.63339273, -0.3905956 ]]))

# Broadcasting

In [2]:
np.random.seed(0)
A = np.random.randint(0, 10, [2, 3])
B = np.ones((2, 3))
A, B

(array([[5, 0, 3],
        [3, 7, 9]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [3]:
A + B

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

In [4]:
A + 5

array([[10,  5,  8],
       [ 8, 12, 14]])