# **Numpy**

In [1]:
import numpy as np

In [2]:
t1 = np.array([1,2,3,4])
t1

array([1, 2, 3, 4])

In [3]:
# nbr lines and nbr Columns
t1.shape

(4,)

In [4]:
# dimension
t1.ndim

1

In [5]:
# size
t1.size

4

### Zeros

In [6]:
z = np.zeros((3,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
z.ndim

2

In [8]:
z.shape

(3, 5)

### Ones

In [9]:
o = np.ones((2,9))
o

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
o.shape

(2, 9)

In [11]:
o.ndim

2

### Full

In [14]:
f = np.full((3,5), 8)
f

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [15]:
# garder les memes random
np.random.seed(0)
np.random.randn(3,5)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323]])

### Identity

In [16]:
i = np.eye((5))
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Linspace

In [17]:
begin = 0
end = 15
quantity = 7
np.linspace(begin, end, quantity)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. ])

### Arange

In [18]:
begin = 0
end = 10
step = 0.5
np.arange(begin, end, step, dtype=np.float16)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5], dtype=float16)

### Manipulation

In [19]:
T1 = np.ones((3,2))
T1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
T2 = np.zeros((3,2))
T2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

#### Assembler deux tableaux

. Horizontal

In [21]:
H = np.hstack((T1, T2))
H

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [22]:
H.shape

(3, 4)

. Vertical

In [23]:
V = np.vstack((T1, T2))
V

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
V.shape

(6, 2)

##### Reshape

In [25]:
Vr = V.reshape((3,4))
Vr

array([[1., 1., 1., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
tab = np.array([1,2,3,4,5])
tab.shape

(5,)

In [27]:
tab = tab.reshape((tab.shape[0],1))
tab.shape

(5, 1)

#### **ravel**

In [28]:
plat = Vr.ravel()
plat

array([1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.])

# **Exercice**

In [29]:
def initialisation(m, n):
    tmp = np.random.randn(m, n)
    O = np.ones((tmp.shape[0], 1))
    T = np.hstack((tmp, O))
    return T

In [30]:
initialisation(2,3)

array([[ 0.33367433,  1.49407907, -0.20515826,  1.        ],
       [ 0.3130677 , -0.85409574, -2.55298982,  1.        ]])